spring.config.import=optional:secrets.properties
spring.application.name=medical-project
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#bez tego konfigu pojawialy sie problemy z nazwami ktore hibernate przyjmowal
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.address=0.0.0.0
#spring.jpa.show-sql=true
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.maximum-pool-size=20
#logging.level.com.zaxxer.hikari=DEBUG


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Dane technicznego u?ytkownika (do prostego logowania)
app.admin.username=${ADMIN_USERNAME:admin}
app.admin.password=${ADMIN_PASSWORD:super_tajne_haslo_123}

# Konfiguracja JWT
app.jwt.secret=${JWT_SECRET:domyslny_klucz_do_testow_lokalnych_minimum_32_znaki}

app.cors.allowed-origins=${FRONTEND_URL:http://localhost:3000}

server.port=${PORT:8080}