spring.config.import=optional:secrets.properties
spring.application.name=medical-project
spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:postgresql://ep-nameless-wind-a9rsgily-pooler.gwc.azure.neon.tech/MedDB?user=MedDB_owner&password=npg_lmcjv2F5TZNY&sslmode=require
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#bez tego konfigu pojawialy sie problemy z nazwami ktore hibernate przyjmowal
spring.jpa.properties.hibernate.physical_naming_strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server.address=0.0.0.0
spring.jpa.show-sql=true
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.maximum-pool-size=20
logging.level.com.zaxxer.hikari=DEBUG